<?php

namespace HomeBuhBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspencesRepository extends EntityRepository
{
}
