home_buh:
    resource: "@HomeBuhBundle/Controller/"
    type:     annotation
    prefix:   /
logout:
    path: /logout
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"