# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        HomeBuhBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db_users:
          entity:
            class: HomeBuhBundle:User
            property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: db_users
            form_login:
                login_path: login
                check_path: login
                username_parameter:  login[username]
                password_parameter:  login[password]
                csrf_parameter:      login[_token]
            logout:
                path: logout
                target: /
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }