<?php

namespace HomeBuhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    public function getAccounts(User $user)
    {
        return $this->findBy(
            [
                "uid" => $user->getId(),
            ],
            [
                "id" => "ASC",
            ]
        );
    }
}
