<?php

namespace HomeBuhBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    public function getExpenses(User $user, $dateFrom, $dateTo) {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select("e")
            ->from("HomeBuhBundle:Expense","e")
            ->where("e.data between :datefrom and :dateto")
            ->andWhere("e.uid = :uid")
            ->setParameter("datefrom", $dateFrom)
            ->setParameter("dateto", $dateTo)
            ->setParameter("uid", $user->getId())
            ->add("orderBy", "e.data desc, e.id desc")
            ->getQuery()
            ->getResult();
    }
}
